<a href="https://colab.research.google.com/github/keonyoung00/AIpython/blob/main/250509.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

## 연습문제 1

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

## 연습문제 2

In [4]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

## 연습문제 3

In [6]:
a = np.array([2, 4, 6])

In [7]:
b = np.array([10, 20 ,30])

In [9]:
c = a * b

In [14]:
c

array([ 20,  80, 180])

## 연습문제 4

In [11]:
c[c > 20]

array([ 80, 180])

# Pandas

In [15]:
import pandas as pd

In [30]:
pd.__version__

'2.2.2'

In [31]:
import os

In [32]:
os.getcwd()

'/content'

In [17]:
s = pd.Series(np.arange(10))

In [18]:
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [20]:
s1 = pd.Series([10, 20 ,30, 40])

In [21]:
s1

0    10
1    20
2    30
3    40
dtype: int64

In [22]:
data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

In [23]:
data

{'이름': ['홍길동', '김철수', '이영희'], '나이': [25, 30, 27], '성별': ['남', '남', '여']}

In [24]:
df = pd.DataFrame(data)

In [25]:
df

이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여

In [27]:
df.to_csv('student.csv', index=False, encoding='utf-8') # DataFrame을 csv파일로 저장, 한글이 있으면 encoding='utf-8'

In [29]:
pd.read_csv('student.csv', encoding='utf-8')

이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여

In [40]:
titanic = pd.read_csv('train_and_test2.csv')

In [42]:
titanic

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1309 rows x 28 columns]

In [41]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [36]:
titanic.describe()

Passengerid          Age         Fare          Sex        sibsp  \
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000   
mean    655.000000    29.503186    33.281086     0.355997     0.498854   
std     378.020061    12.905241    51.741500     0.478997     1.041658   
min       1.000000     0.170000     0.000000     0.000000     0.000000   
25%     328.000000    22.000000     7.895800     0.000000     0.000000   
50%     655.000000    28.000000    14.454200     0.000000     0.000000   
75%     982.000000    35.000000    31.275000     1.000000     1.000000   
max    1309.000000    80.000000   512.329200     1.000000     8.000000   

         zero  zero.1  zero.2  zero.3  zero.4  ...  zero.12  zero.13  zero.14  \
count  1309.0  1309.0  1309.0  1309.0  1309.0  ...   1309.0   1309.0   1309.0   
mean      0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
std       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
min       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
25%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
50%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
75%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
max       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   

            Pclass  zero.15  zero.16     Embarked  zero.17  zero.18  \
count  1309.000000   1309.0   1309.0  1307.000000   1309.0   1309.0   
mean      2.294882      0.0      0.0     1.492731      0.0      0.0   
std       0.837836      0.0      0.0     0.814626      0.0      0.0   
min       1.000000      0.0      0.0     0.000000      0.0      0.0   
25%       2.000000      0.0      0.0     1.000000      0.0      0.0   
50%       3.000000      0.0      0.0     2.000000      0.0      0.0   
75%       3.000000      0.0      0.0     2.000000      0.0      0.0   
max       3.000000      0.0      0.0     2.000000      0.0      0.0   

          2urvived  
count  1309.000000  
mean      0.261268  
std       0.439494  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000  

[8 rows x 28 columns]

In [43]:
titanic.dropna(inplace=True)

In [44]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1307 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1307 non-null   int64  
 1   Age          1307 non-null   float64
 2   Fare         1307 non-null   float64
 3   Sex          1307 non-null   int64  
 4   sibsp        1307 non-null   int64  
 5   zero         1307 non-null   int64  
 6   zero.1       1307 non-null   int64  
 7   zero.2       1307 non-null   int64  
 8   zero.3       1307 non-null   int64  
 9   zero.4       1307 non-null   int64  
 10  zero.5       1307 non-null   int64  
 11  zero.6       1307 non-null   int64  
 12  Parch        1307 non-null   int64  
 13  zero.7       1307 non-null   int64  
 14  zero.8       1307 non-null   int64  
 15  zero.9       1307 non-null   int64  
 16  zero.10      1307 non-null   int64  
 17  zero.11      1307 non-null   int64  
 18  zero.12      1307 non-null   int64  
 19  zero.13    

In [47]:
titanic.groupby('Sex')['Age'].mean()

Sex
0    30.017888
1    28.479720
Name: Age, dtype: float64